### ISSUE TITLE
Can't switch to other contact

### ISSUE THREAD

**Issue by maicol07** [rafaismyname/WhatsBuddy#3]
Hi,
If I open the profile of a contact or the infos of a group, I can't switch to another chat and I need to reload WA Web.
Can you solve this?
Thanks

**Comment by rafaismyname** [comment]
Hey @maicol07!

I'm super sorry that I haven't noticed your ticket until today! (#5)
I just released a new version and it seems that your described issue has been fixed :)

Let me know if you have any other issues
